[project]
name = "covered-call"
authors = ["cargocult"]
description = "This contract allows for the creation, transfer, exercise, and underlying reclamation needed for covered calls"
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.covered-call]
path = "contracts/covered-call.clar"
depends_on = ["sip010-ft-trait", "sip009-nft-trait", "wrapped-usdc"]

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"
depends_on = []

[contracts.wrapped-usdc]
path = "contracts/wrapped-usdc.clar"
depends_on = ["sip010-ft-trait"]
